baseurl: "https://songqi.online/"
languageCode: "en-us"
title: "Songqi Duan | 段松岐"
theme: "hugo-ivy"
disqusShortname: "duansq"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"
  data2vis: "/data2vis/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
    - name: "Data2Vis"
      url: "/data2vis/"
      weight: 5
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "English"
      url: "/en/"
      weight: 5

  data2vis:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "R Gallery"
      url: "/data2vis/"
      weight: 2
    - name: "Python Gallery"
      url: "/data2vis/caveats"
      weight: 3
params:
  description: "Personal website of Songqi Duan; 段松岐的个人网站"
  footer: "&copy; [Songqi Duan](/) 2018 - 2020"
  disqusURL: "https://songqi.online"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/zerostwo/songqi.online/edit/master/content/"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Songqi Duan"
      tag: ""

  author:
    en: "Songqi Duan"
    cn: "段松岐"
    data2vis: "段松岐"

  lang:
    edit:
      cn: "编辑"
      data2vis: "编辑"
    license:
      cn: "版权"
      data2vis: "版权"
    subscribe:
      cn: "订阅"
      data2vis: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
